name: vale
description: "Your Talking Journal."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  record: ^6.1.2
  path_provider: ^2.1.5
  just_audio: ^0.10.5
  path: ^1.9.1
  waveform_flutter: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - images/
